name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - 'branch-b'

jobs:
    unit-testing:
        name: Unit Testing
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 22
    
        - name: Install Dependencies
          run: npm install